### PR TITLE
Add Edge instance for List

### PR DESCRIPTION
**Pull request by swapnilraj**

### CODE REVIEW

**Comment by csicar** [comment]
The `prelude.list Cons` test is failing for me. Maybe the value isn't updated?

**Comment by swapnilraj** [comment]
Oh yeah I forgot to commit the change

**Comment by csicar** [comment]
No problem.

I think I would still prefer to have the `Cons` constructor name explicitly in the nodes. (Like `Cons'` in http://bit.ly/2TifUZr).

Do you see a reason for introducing a special case (in terms of the layout) for `List`?

**Comment by swapnilraj** [comment]
`List` is essentially a linked-list which is better represented/visualised with http://bit.ly/2TBqrhq.

On a more informal note, the Cons nodes just fee like noise

**Comment by csicar** [comment]
It probably is just noise, but keeps consistency with the generic deriving of the `List` structure.
So I think the right solution is to reduce the noise for all Constructors and remove the special case for `List`. I'm thinking of something like [this](http://bit.ly/2VJEAfg):
grafik

I think that's a little too much for this PR. So I'll merge this for now and may come back to this later.

**Pull request merged**
